spring:
  application:
    name: feed-service

  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://collector:4317

  data:
    cassandra:
      keyspace-name: spring_cassandra
      contact-points: cassandra
      port: 9042
      schema-action: CREATE_IF_NOT_EXISTS
      local-datacenter: datacenter1

  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
          configuration:
            key:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bindings:
        momentsPostChanged:
          destination: moments.post.changed
          contentType: application/json
          group: graphService
          consumer:
            startOffset: latest
            autoCommitOffset: false

server:
  port: 8092

eureka:
  instance:
    hostname: service-discovery
    prefer-ip-address: true
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

application:
  cache: # Cache configuration
    hazelcast: # Hazelcast distributed cache
      time-to-live-seconds: 3600
      backup-count: 1
  registry:
    password: admin
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: NmU2ZWI0NTdhYTY1MTlmMjYwNWJlZDIzNTczMDI3OTdhNmYyN2U5ZDdiYWE5ZDVhOTQyYTJkZTc1NzQxN2M4OWJhNWJmMDgwN2M5ZWZiYmNjOGYyZDA0ODYwOWJjM2Q2MGM2YjhiMjMyMmVjN2ZiZWQyMWZhNDE0MTY4MDcwN2Y=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512