spring:
  application:
    name: api-gateway

  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://collector:4317

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/users/**, /api/authenticate/**
        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/posts/**
        - id: graph-service
          uri: lb://GRAPH-SERVICE
          predicates:
            - Path=/api/graph/**
        - id: feed-service
          uri: lb://FEED-SERVICE
          predicates:
            - Path=/api/feed/**

server:
  port: 8080

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 600000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

eureka:
  instance:
    hostname: service-discovery
    prefer-ip-address: true
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
