spring:
  application:
    name: post-service

  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://collector:4317

  data:
    mongodb:
      uri: mongodb://mongodb:27017/instaclone_post
      database: instaclone_post

  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
          configuration:
            key:
              serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        postChanged:
          destination: instagram.post.changed
          contentType: application/json

server:
  port: 8096

eureka:
  instance:
    hostname: service-discovery
    prefer-ip-address: true
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/

application:
  cache: # Cache configuration
    hazelcast: # Hazelcast distributed cache
      time-to-live-seconds: 3600
      backup-count: 1
  registry:
    password: admin
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: NmU2ZWI0NTdhYTY1MTlmMjYwNWJlZDIzNTczMDI3OTdhNmYyN2U5ZDdiYWE5ZDVhOTQyYTJkZTc1NzQxN2M4OWJhNWJmMDgwN2M5ZWZiYmNjOGYyZDA0ODYwOWJjM2Q2MGM2YjhiMjMyMmVjN2ZiZWQyMWZhNDE0MTY4MDcwN2Y=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512