spring:
  application:
    name: post-service

  data:
    mongodb:
      database: instaclone_post

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            key:
              serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        momentsPostChanged:
          destination: moments.post.changed
          contentType: application/json

server:
  port: 8001

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

application:
  cache: # Cache configuration
    hazelcast: # Hazelcast distributed cache
      time-to-live-seconds: 3600
      backup-count: 1
  registry:
    password: admin
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: NmU2ZWI0NTdhYTY1MTlmMjYwNWJlZDIzNTczMDI3OTdhNmYyN2U5ZDdiYWE5ZDVhOTQyYTJkZTc1NzQxN2M4OWJhNWJmMDgwN2M5ZWZiYmNjOGYyZDA0ODYwOWJjM2Q2MGM2YjhiMjMyMmVjN2ZiZWQyMWZhNDE0MTY4MDcwN2Y=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512