server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: lb://FIRST-SERVICE
          predicates:
            - Path=/first/**
        - id: graph-service
          uri: lb://GRAPH-SERVICE
          predicates:
            - Path=/api/graph/users/**
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/users/**, /api/authenticate/**
